baseURL = 'https://landier.co/'
languageCode = 'en-us'
title = 'Nicolas Landier - Data Expert'
theme = 'hugo-initio'


[params]
    name = "Nicolas Landier"
    description = "Data Expert"
    email = "nicolas@landier.co"
    phone = ""
    address = "Paris, France"
    year = 2023
    avatar = "images/guy.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "G-K3EC9WXXZK"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/landier"
    icon = "fab fa-facebook-square"
    footer = false
    sharethis = false
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/landier"
    icon = "fab fa-twitter-square"
    footer = false
    sharethis = false
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nicolas.lndr"
    icon = "fab fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/landier"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/landier"
    icon = "fab fa-github"
    footer = true
    sharethis = true
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:nicolas@landier.co"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
